#!/usr/bin/env python
# encoding: utf-8



##### Hello! This is where I'm keeping my command line calls for running clustal omega


###write all the sequences that need to be aligned into one fasta file using biopython.

### pass the alignment on to clustal o
##A typical invocation would be: clustalo -i my-in-seqs.fa -o my-out-seqs.fa -v

#clustalo -i 918_probe0.fa --profile1 918.fa -o 918.PARTIAL.fa --outfmt phylip

#clustalo -i probe1.fa --profile1 918.fa -o 918.DONE.fa --outfmt phylip

