#!/usr/bin/env python
# encoding: utf-8



##### Hello! This is where I'm keeping my command line calls for running clustal omega


###write all the sequences that need to be aligned into one fasta file using biopython.
##First convert the probe fasta files to a nexus files. 

from Bio import SeqIO
records = SeqIO.parse("918_oryLat2_chr1_16673522_16673701|probe_0|1,121.fasta", "fasta")
count = SeqIO.write(records,"918_probe0.nexus", "nexus")
print("Converted %i records" % count)

### pass the alignment on to clustal o
##A typical invocation would be: clustalo -i my-in-seqs.fa -o my-out-seqs.fa -v

#clustalo -i 


